// Original Author: Sean Long @ Hailstone Software
// Contact: 		sean@hailstonesoftware.com
// Last Modified:   02/14/2000
#define SPEAKIT_WORK			B_SPECIFIERS_END+1	 
#define SPEAKIT_CLEAR      	 	B_SPECIFIERS_END+2   
#define SPEAKIT_FONT_10			B_SPECIFIERS_END+3
#define SPEAKIT_FONT_12			B_SPECIFIERS_END+4
#define SPEAKIT_FONT_14			B_SPECIFIERS_END+5
#define SPEAKIT_FONT_18			B_SPECIFIERS_END+6
#define SPEAKIT_FONT_24			B_SPECIFIERS_END+7
#define SPEAKIT_FONT_36			B_SPECIFIERS_END+8

#define SPEAKIT_COLOR_OTHER     B_SPECIFIERS_END+9

#define SPEAKIT_SETTINGS        B_SPECIFIERS_END+10
#define SPEAKIT_VOL_CHANGE		B_SPECIFIERS_END+11
#define SPEAKIT_SETWIN_QUIT		B_SPECIFIERS_END+12
#define SPEAKIT_HIGHLIGHT_CHANGE B_SPECIFIERS_END+13

#define SPEAKIT_COLORWIN_QUIT   B_SPECIFIERS_END+14
#define	SPEAKIT_COLORWIN_CHANGE B_SPECIFIERS_END+15

#define SPEAKIT_CHAR_LEN_CHANGE B_SPECIFIERS_END+16
//#define SPEAKIT_END_VARS		B_SPECIFIERS_END+16

#define MENU_FILE_OPEN			B_SPECIFIERS_END+17
#define MENU_FILE_NEW			B_SPECIFIERS_END+18
#define MENU_FILE_SAVE			B_SPECIFIERS_END+19
#define MENU_FILE_SAVEAS		B_SPECIFIERS_END+20
